<?php

/**
 * Base class that represents a row from the 'raids' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 04/05/09 15:30:18
 *
 * @package    lib.model.om
 */
abstract class BaseRaids extends BaseObject  implements Persistent {


  const PEER = 'RaidsPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        RaidsPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the note field.
	 * @var        string
	 */
	protected $note;

	/**
	 * The value for the boss field.
	 * @var        int
	 */
	protected $boss;

	/**
	 * The value for the baseval field.
	 * Note: this column has a database default value of: 100
	 * @var        double
	 */
	protected $baseval;

	/**
	 * The value for the inflatedval field.
	 * Note: this column has a database default value of: 100
	 * @var        double
	 */
	protected $inflatedval;

	/**
	 * The value for the date field.
	 * @var        string
	 */
	protected $date;

	/**
	 * @var        Bosses
	 */
	protected $aBosses;

	/**
	 * @var        array Attendees[] Collection to store aggregation of Attendees objects.
	 */
	protected $collAttendeess;

	/**
	 * @var        Criteria The criteria used to select the current contents of collAttendeess.
	 */
	private $lastAttendeesCriteria = null;

	/**
	 * @var        array Items[] Collection to store aggregation of Items objects.
	 */
	protected $collItemss;

	/**
	 * @var        Criteria The criteria used to select the current contents of collItemss.
	 */
	private $lastItemsCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseRaids object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->baseval = 100;
		$this->inflatedval = 100;
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [note] column value.
	 * 
	 * @return     string
	 */
	public function getNote()
	{
		return $this->note;
	}

	/**
	 * Get the [boss] column value.
	 * 
	 * @return     int
	 */
	public function getBoss()
	{
		return $this->boss;
	}

	/**
	 * Get the [baseval] column value.
	 * 
	 * @return     double
	 */
	public function getBaseval()
	{
		return $this->baseval;
	}

	/**
	 * Get the [inflatedval] column value.
	 * 
	 * @return     double
	 */
	public function getInflatedval()
	{
		return $this->inflatedval;
	}

	/**
	 * Get the [optionally formatted] temporal [date] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getDate($format = 'Y-m-d H:i:s')
	{
		if ($this->date === null) {
			return null;
		}


		if ($this->date === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->date);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->date, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Raids The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = RaidsPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [note] column.
	 * 
	 * @param      string $v new value
	 * @return     Raids The current object (for fluent API support)
	 */
	public function setNote($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->note !== $v) {
			$this->note = $v;
			$this->modifiedColumns[] = RaidsPeer::NOTE;
		}

		return $this;
	} // setNote()

	/**
	 * Set the value of [boss] column.
	 * 
	 * @param      int $v new value
	 * @return     Raids The current object (for fluent API support)
	 */
	public function setBoss($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->boss !== $v) {
			$this->boss = $v;
			$this->modifiedColumns[] = RaidsPeer::BOSS;
		}

		if ($this->aBosses !== null && $this->aBosses->getId() !== $v) {
			$this->aBosses = null;
		}

		return $this;
	} // setBoss()

	/**
	 * Set the value of [baseval] column.
	 * 
	 * @param      double $v new value
	 * @return     Raids The current object (for fluent API support)
	 */
	public function setBaseval($v)
	{
		if ($v !== null) {
			$v = (double) $v;
		}

		if ($this->baseval !== $v || $v === 100) {
			$this->baseval = $v;
			$this->modifiedColumns[] = RaidsPeer::BASEVAL;
		}

		return $this;
	} // setBaseval()

	/**
	 * Set the value of [inflatedval] column.
	 * 
	 * @param      double $v new value
	 * @return     Raids The current object (for fluent API support)
	 */
	public function setInflatedval($v)
	{
		if ($v !== null) {
			$v = (double) $v;
		}

		if ($this->inflatedval !== $v || $v === 100) {
			$this->inflatedval = $v;
			$this->modifiedColumns[] = RaidsPeer::INFLATEDVAL;
		}

		return $this;
	} // setInflatedval()

	/**
	 * Sets the value of [date] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Raids The current object (for fluent API support)
	 */
	public function setDate($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->date !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->date !== null && $tmpDt = new DateTime($this->date)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->date = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = RaidsPeer::DATE;
			}
		} // if either are not null

		return $this;
	} // setDate()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array(RaidsPeer::BASEVAL,RaidsPeer::INFLATEDVAL))) {
				return false;
			}

			if ($this->baseval !== 100) {
				return false;
			}

			if ($this->inflatedval !== 100) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->note = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->boss = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->baseval = ($row[$startcol + 3] !== null) ? (double) $row[$startcol + 3] : null;
			$this->inflatedval = ($row[$startcol + 4] !== null) ? (double) $row[$startcol + 4] : null;
			$this->date = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 6; // 6 = RaidsPeer::NUM_COLUMNS - RaidsPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Raids object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aBosses !== null && $this->boss !== $this->aBosses->getId()) {
			$this->aBosses = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(RaidsPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = RaidsPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aBosses = null;
			$this->collAttendeess = null;
			$this->lastAttendeesCriteria = null;

			$this->collItemss = null;
			$this->lastItemsCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseRaids:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(RaidsPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			RaidsPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseRaids:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseRaids:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(RaidsPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseRaids:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			RaidsPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aBosses !== null) {
				if ($this->aBosses->isModified() || $this->aBosses->isNew()) {
					$affectedRows += $this->aBosses->save($con);
				}
				$this->setBosses($this->aBosses);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = RaidsPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = RaidsPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += RaidsPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collAttendeess !== null) {
				foreach ($this->collAttendeess as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collItemss !== null) {
				foreach ($this->collItemss as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aBosses !== null) {
				if (!$this->aBosses->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aBosses->getValidationFailures());
				}
			}


			if (($retval = RaidsPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collAttendeess !== null) {
					foreach ($this->collAttendeess as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collItemss !== null) {
					foreach ($this->collItemss as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = RaidsPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getNote();
				break;
			case 2:
				return $this->getBoss();
				break;
			case 3:
				return $this->getBaseval();
				break;
			case 4:
				return $this->getInflatedval();
				break;
			case 5:
				return $this->getDate();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = RaidsPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getNote(),
			$keys[2] => $this->getBoss(),
			$keys[3] => $this->getBaseval(),
			$keys[4] => $this->getInflatedval(),
			$keys[5] => $this->getDate(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = RaidsPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setNote($value);
				break;
			case 2:
				$this->setBoss($value);
				break;
			case 3:
				$this->setBaseval($value);
				break;
			case 4:
				$this->setInflatedval($value);
				break;
			case 5:
				$this->setDate($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = RaidsPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setNote($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setBoss($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setBaseval($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setInflatedval($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setDate($arr[$keys[5]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(RaidsPeer::DATABASE_NAME);

		if ($this->isColumnModified(RaidsPeer::ID)) $criteria->add(RaidsPeer::ID, $this->id);
		if ($this->isColumnModified(RaidsPeer::NOTE)) $criteria->add(RaidsPeer::NOTE, $this->note);
		if ($this->isColumnModified(RaidsPeer::BOSS)) $criteria->add(RaidsPeer::BOSS, $this->boss);
		if ($this->isColumnModified(RaidsPeer::BASEVAL)) $criteria->add(RaidsPeer::BASEVAL, $this->baseval);
		if ($this->isColumnModified(RaidsPeer::INFLATEDVAL)) $criteria->add(RaidsPeer::INFLATEDVAL, $this->inflatedval);
		if ($this->isColumnModified(RaidsPeer::DATE)) $criteria->add(RaidsPeer::DATE, $this->date);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(RaidsPeer::DATABASE_NAME);

		$criteria->add(RaidsPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Raids (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setNote($this->note);

		$copyObj->setBoss($this->boss);

		$copyObj->setBaseval($this->baseval);

		$copyObj->setInflatedval($this->inflatedval);

		$copyObj->setDate($this->date);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getAttendeess() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addAttendees($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getItemss() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addItems($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Raids Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     RaidsPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new RaidsPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Bosses object.
	 *
	 * @param      Bosses $v
	 * @return     Raids The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setBosses(Bosses $v = null)
	{
		if ($v === null) {
			$this->setBoss(NULL);
		} else {
			$this->setBoss($v->getId());
		}

		$this->aBosses = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Bosses object, it will not be re-added.
		if ($v !== null) {
			$v->addRaids($this);
		}

		return $this;
	}


	/**
	 * Get the associated Bosses object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Bosses The associated Bosses object.
	 * @throws     PropelException
	 */
	public function getBosses(PropelPDO $con = null)
	{
		if ($this->aBosses === null && ($this->boss !== null)) {
			$c = new Criteria(BossesPeer::DATABASE_NAME);
			$c->add(BossesPeer::ID, $this->boss);
			$this->aBosses = BossesPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aBosses->addRaidss($this);
			 */
		}
		return $this->aBosses;
	}

	/**
	 * Clears out the collAttendeess collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addAttendeess()
	 */
	public function clearAttendeess()
	{
		$this->collAttendeess = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collAttendeess collection (array).
	 *
	 * By default this just sets the collAttendeess collection to an empty array (like clearcollAttendeess());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initAttendeess()
	{
		$this->collAttendeess = array();
	}

	/**
	 * Gets an array of Attendees objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Raids has previously been saved, it will retrieve
	 * related Attendeess from storage. If this Raids is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Attendees[]
	 * @throws     PropelException
	 */
	public function getAttendeess($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(RaidsPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collAttendeess === null) {
			if ($this->isNew()) {
			   $this->collAttendeess = array();
			} else {

				$criteria->add(AttendeesPeer::RAIDS_ID, $this->id);

				AttendeesPeer::addSelectColumns($criteria);
				$this->collAttendeess = AttendeesPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(AttendeesPeer::RAIDS_ID, $this->id);

				AttendeesPeer::addSelectColumns($criteria);
				if (!isset($this->lastAttendeesCriteria) || !$this->lastAttendeesCriteria->equals($criteria)) {
					$this->collAttendeess = AttendeesPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastAttendeesCriteria = $criteria;
		return $this->collAttendeess;
	}

	/**
	 * Returns the number of related Attendees objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Attendees objects.
	 * @throws     PropelException
	 */
	public function countAttendeess(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(RaidsPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collAttendeess === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(AttendeesPeer::RAIDS_ID, $this->id);

				$count = AttendeesPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(AttendeesPeer::RAIDS_ID, $this->id);

				if (!isset($this->lastAttendeesCriteria) || !$this->lastAttendeesCriteria->equals($criteria)) {
					$count = AttendeesPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collAttendeess);
				}
			} else {
				$count = count($this->collAttendeess);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Attendees object to this object
	 * through the Attendees foreign key attribute.
	 *
	 * @param      Attendees $l Attendees
	 * @return     void
	 * @throws     PropelException
	 */
	public function addAttendees(Attendees $l)
	{
		if ($this->collAttendeess === null) {
			$this->initAttendeess();
		}
		if (!in_array($l, $this->collAttendeess, true)) { // only add it if the **same** object is not already associated
			array_push($this->collAttendeess, $l);
			$l->setRaids($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Raids is new, it will return
	 * an empty collection; or if this Raids has previously
	 * been saved, it will retrieve related Attendeess from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Raids.
	 */
	public function getAttendeessJoinRoster($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(RaidsPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collAttendeess === null) {
			if ($this->isNew()) {
				$this->collAttendeess = array();
			} else {

				$criteria->add(AttendeesPeer::RAIDS_ID, $this->id);

				$this->collAttendeess = AttendeesPeer::doSelectJoinRoster($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(AttendeesPeer::RAIDS_ID, $this->id);

			if (!isset($this->lastAttendeesCriteria) || !$this->lastAttendeesCriteria->equals($criteria)) {
				$this->collAttendeess = AttendeesPeer::doSelectJoinRoster($criteria, $con, $join_behavior);
			}
		}
		$this->lastAttendeesCriteria = $criteria;

		return $this->collAttendeess;
	}

	/**
	 * Clears out the collItemss collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addItemss()
	 */
	public function clearItemss()
	{
		$this->collItemss = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collItemss collection (array).
	 *
	 * By default this just sets the collItemss collection to an empty array (like clearcollItemss());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initItemss()
	{
		$this->collItemss = array();
	}

	/**
	 * Gets an array of Items objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Raids has previously been saved, it will retrieve
	 * related Itemss from storage. If this Raids is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Items[]
	 * @throws     PropelException
	 */
	public function getItemss($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(RaidsPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collItemss === null) {
			if ($this->isNew()) {
			   $this->collItemss = array();
			} else {

				$criteria->add(ItemsPeer::RAIDID, $this->id);

				ItemsPeer::addSelectColumns($criteria);
				$this->collItemss = ItemsPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(ItemsPeer::RAIDID, $this->id);

				ItemsPeer::addSelectColumns($criteria);
				if (!isset($this->lastItemsCriteria) || !$this->lastItemsCriteria->equals($criteria)) {
					$this->collItemss = ItemsPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastItemsCriteria = $criteria;
		return $this->collItemss;
	}

	/**
	 * Returns the number of related Items objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Items objects.
	 * @throws     PropelException
	 */
	public function countItemss(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(RaidsPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collItemss === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(ItemsPeer::RAIDID, $this->id);

				$count = ItemsPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(ItemsPeer::RAIDID, $this->id);

				if (!isset($this->lastItemsCriteria) || !$this->lastItemsCriteria->equals($criteria)) {
					$count = ItemsPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collItemss);
				}
			} else {
				$count = count($this->collItemss);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Items object to this object
	 * through the Items foreign key attribute.
	 *
	 * @param      Items $l Items
	 * @return     void
	 * @throws     PropelException
	 */
	public function addItems(Items $l)
	{
		if ($this->collItemss === null) {
			$this->initItemss();
		}
		if (!in_array($l, $this->collItemss, true)) { // only add it if the **same** object is not already associated
			array_push($this->collItemss, $l);
			$l->setRaids($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Raids is new, it will return
	 * an empty collection; or if this Raids has previously
	 * been saved, it will retrieve related Itemss from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Raids.
	 */
	public function getItemssJoinRoster($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(RaidsPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collItemss === null) {
			if ($this->isNew()) {
				$this->collItemss = array();
			} else {

				$criteria->add(ItemsPeer::RAIDID, $this->id);

				$this->collItemss = ItemsPeer::doSelectJoinRoster($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(ItemsPeer::RAIDID, $this->id);

			if (!isset($this->lastItemsCriteria) || !$this->lastItemsCriteria->equals($criteria)) {
				$this->collItemss = ItemsPeer::doSelectJoinRoster($criteria, $con, $join_behavior);
			}
		}
		$this->lastItemsCriteria = $criteria;

		return $this->collItemss;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collAttendeess) {
				foreach ((array) $this->collAttendeess as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collItemss) {
				foreach ((array) $this->collItemss as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collAttendeess = null;
		$this->collItemss = null;
			$this->aBosses = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseRaids:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseRaids::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseRaids
