<?php

/**
 * BaseAdministrator
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $accountId
 * @property datetime $lastLogin
 * @property Account $Account
 * 
 * @method integer       getId()        Returns the current record's "id" value
 * @method integer       getAccountId() Returns the current record's "accountId" value
 * @method datetime      getLastLogin() Returns the current record's "lastLogin" value
 * @method Account       getAccount()   Returns the current record's "Account" value
 * @method Administrator setId()        Sets the current record's "id" value
 * @method Administrator setAccountId() Sets the current record's "accountId" value
 * @method Administrator setLastLogin() Sets the current record's "lastLogin" value
 * @method Administrator setAccount()   Sets the current record's "Account" value
 * 
 * @package    gtonline
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdministrator extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('administrator');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('accountId', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('lastLogin', 'datetime', null, array(
             'type' => 'datetime',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Account', array(
             'local' => 'accountId',
             'foreign' => 'id'));
    }
}