<?php

/**
 * BaseStatusUpdate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $userId
 * @property datetime $created_at
 * @property string $text
 * @property User $User
 * @property Doctrine_Collection $StatusUpdateComment
 * 
 * @method integer             getId()                  Returns the current record's "id" value
 * @method integer             getUserId()              Returns the current record's "userId" value
 * @method datetime            getCreatedAt()           Returns the current record's "created_at" value
 * @method string              getText()                Returns the current record's "text" value
 * @method User                getUser()                Returns the current record's "User" value
 * @method Doctrine_Collection getStatusUpdateComment() Returns the current record's "StatusUpdateComment" collection
 * @method StatusUpdate        setId()                  Sets the current record's "id" value
 * @method StatusUpdate        setUserId()              Sets the current record's "userId" value
 * @method StatusUpdate        setCreatedAt()           Sets the current record's "created_at" value
 * @method StatusUpdate        setText()                Sets the current record's "text" value
 * @method StatusUpdate        setUser()                Sets the current record's "User" value
 * @method StatusUpdate        setStatusUpdateComment() Sets the current record's "StatusUpdateComment" collection
 * 
 * @package    gtonline
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStatusUpdate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('status_update');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('userId', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('created_at', 'datetime', null, array(
             'type' => 'datetime',
             'notnull' => true,
             ));
        $this->hasColumn('text', 'string', 512, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 512,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'userId',
             'foreign' => 'id'));

        $this->hasMany('StatusUpdateComment', array(
             'local' => 'id',
             'foreign' => 'statusUpdateId'));
    }
}