<?php

/**
 * BaseUserSchool
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $userId
 * @property integer $schoolId
 * @property integer $graduationYear
 * @property User $User
 * @property School $School
 * 
 * @method integer    getId()             Returns the current record's "id" value
 * @method integer    getUserId()         Returns the current record's "userId" value
 * @method integer    getSchoolId()       Returns the current record's "schoolId" value
 * @method integer    getGraduationYear() Returns the current record's "graduationYear" value
 * @method User       getUser()           Returns the current record's "User" value
 * @method School     getSchool()         Returns the current record's "School" value
 * @method UserSchool setId()             Sets the current record's "id" value
 * @method UserSchool setUserId()         Sets the current record's "userId" value
 * @method UserSchool setSchoolId()       Sets the current record's "schoolId" value
 * @method UserSchool setGraduationYear() Sets the current record's "graduationYear" value
 * @method UserSchool setUser()           Sets the current record's "User" value
 * @method UserSchool setSchool()         Sets the current record's "School" value
 * 
 * @package    gtonline
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserSchool extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_school');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('userId', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('schoolId', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('graduationYear', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'userId',
             'foreign' => 'id'));

        $this->hasOne('School', array(
             'local' => 'schoolId',
             'foreign' => 'id'));
    }
}