<?php

/**
 * BaseUserInterest
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $userId
 * @property string $description
 * @property User $User
 * 
 * @method integer      getId()          Returns the current record's "id" value
 * @method integer      getUserId()      Returns the current record's "userId" value
 * @method string       getDescription() Returns the current record's "description" value
 * @method User         getUser()        Returns the current record's "User" value
 * @method UserInterest setId()          Sets the current record's "id" value
 * @method UserInterest setUserId()      Sets the current record's "userId" value
 * @method UserInterest setDescription() Sets the current record's "description" value
 * @method UserInterest setUser()        Sets the current record's "User" value
 * 
 * @package    gtonline
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserInterest extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_interest');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('userId', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'userId',
             'foreign' => 'id'));
    }
}