<?php

/**
 * BaseAccount
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $email
 * @property string $password
 * @property string $firstname
 * @property string $lastname
 * @property boolean $isAdmin
 * @property Doctrine_Collection $User
 * @property Doctrine_Collection $Administrator
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method string              getEmail()         Returns the current record's "email" value
 * @method string              getPassword()      Returns the current record's "password" value
 * @method string              getFirstname()     Returns the current record's "firstname" value
 * @method string              getLastname()      Returns the current record's "lastname" value
 * @method boolean             getIsAdmin()       Returns the current record's "isAdmin" value
 * @method Doctrine_Collection getUser()          Returns the current record's "User" collection
 * @method Doctrine_Collection getAdministrator() Returns the current record's "Administrator" collection
 * @method Account             setId()            Sets the current record's "id" value
 * @method Account             setEmail()         Sets the current record's "email" value
 * @method Account             setPassword()      Sets the current record's "password" value
 * @method Account             setFirstname()     Sets the current record's "firstname" value
 * @method Account             setLastname()      Sets the current record's "lastname" value
 * @method Account             setIsAdmin()       Sets the current record's "isAdmin" value
 * @method Account             setUser()          Sets the current record's "User" collection
 * @method Account             setAdministrator() Sets the current record's "Administrator" collection
 * 
 * @package    gtonline
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAccount extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('account');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('password', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('firstname', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('lastname', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('isAdmin', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('User', array(
             'local' => 'id',
             'foreign' => 'accountId'));

        $this->hasMany('Administrator', array(
             'local' => 'id',
             'foreign' => 'accountId'));
    }
}