<?php

/**
 * BaseSchoolType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $School
 * 
 * @method integer             getId()     Returns the current record's "id" value
 * @method string              getName()   Returns the current record's "name" value
 * @method Doctrine_Collection getSchool() Returns the current record's "School" collection
 * @method SchoolType          setId()     Sets the current record's "id" value
 * @method SchoolType          setName()   Sets the current record's "name" value
 * @method SchoolType          setSchool() Sets the current record's "School" collection
 * 
 * @package    gtonline
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSchoolType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('school_type');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('School', array(
             'local' => 'id',
             'foreign' => 'school_type_id'));
    }
}