<?php

/**
 * BaseStatusUpdateComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $statusUpdateId
 * @property datetime $created_at
 * @property string $text
 * @property integer $userId
 * @property User $User
 * @property StatusUpdate $StatusUpdate
 * 
 * @method integer             getId()             Returns the current record's "id" value
 * @method integer             getStatusUpdateId() Returns the current record's "statusUpdateId" value
 * @method datetime            getCreatedAt()      Returns the current record's "created_at" value
 * @method string              getText()           Returns the current record's "text" value
 * @method integer             getUserId()         Returns the current record's "userId" value
 * @method User                getUser()           Returns the current record's "User" value
 * @method StatusUpdate        getStatusUpdate()   Returns the current record's "StatusUpdate" value
 * @method StatusUpdateComment setId()             Sets the current record's "id" value
 * @method StatusUpdateComment setStatusUpdateId() Sets the current record's "statusUpdateId" value
 * @method StatusUpdateComment setCreatedAt()      Sets the current record's "created_at" value
 * @method StatusUpdateComment setText()           Sets the current record's "text" value
 * @method StatusUpdateComment setUserId()         Sets the current record's "userId" value
 * @method StatusUpdateComment setUser()           Sets the current record's "User" value
 * @method StatusUpdateComment setStatusUpdate()   Sets the current record's "StatusUpdate" value
 * 
 * @package    gtonline
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStatusUpdateComment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('status_update_comment');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('statusUpdateId', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('created_at', 'datetime', null, array(
             'type' => 'datetime',
             'notnull' => true,
             ));
        $this->hasColumn('text', 'string', 512, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 512,
             ));
        $this->hasColumn('userId', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'userId',
             'foreign' => 'id'));

        $this->hasOne('StatusUpdate', array(
             'local' => 'statusUpdateId',
             'foreign' => 'id'));
    }
}