<?php

/**
 * BaseSchool
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property enum $type
 * @property Doctrine_Collection $UserSchool
 * 
 * @method integer             getId()         Returns the current record's "id" value
 * @method string              getName()       Returns the current record's "name" value
 * @method enum                getType()       Returns the current record's "type" value
 * @method Doctrine_Collection getUserSchool() Returns the current record's "UserSchool" collection
 * @method School              setId()         Sets the current record's "id" value
 * @method School              setName()       Sets the current record's "name" value
 * @method School              setType()       Sets the current record's "type" value
 * @method School              setUserSchool() Sets the current record's "UserSchool" collection
 * 
 * @package    gtonline
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSchool extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('school');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('type', 'enum', null, array(
             'type' => 'enum',
             'notnull' => true,
             'values' => 
             array(
              0 => 'College/University',
              1 => 'High School',
              2 => 'Middle School',
              3 => 'Elementary School',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('UserSchool', array(
             'local' => 'id',
             'foreign' => 'schoolId'));
    }
}