using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Asuah.WarcraftPCap
{

    // PacketID Constants for C# (C Sharp) 
    // Generated by BNETDocs: Redux on June 1, 2009 
    // BNETDocs: Redux software written by Don Cullen AKA Kyro
    // Original BNETDocs content compiled by Arta & Skywing

    public enum PacketIDConstants : byte
    {

	    // Battle.net Messages Constants
	    // -------------------

	    Null = 0x00,
	    StopAdv = 0x02,
	    ServerList = 0x04,
	    ClientID = 0x05,
	    StartVersioning = 0x06,
	    ReportVersion = 0x07,
	    StartAdvEx = 0x08,
	    GetAdvListEx = 0x09,
	    EnterChat = 0x0A,
	    GetChannelList = 0x0B,
	    JoinChannel = 0x0C,
	    ChatCommand = 0x0E,
	    ChatEvent = 0x0F,
	    LeaveChat = 0x10,
	    LocaleInfo = 0x12,
	    FloodDetected = 0x13,
	    UDPPingResponse = 0x14,
	    CheckAd = 0x15,
	    ClickAd = 0x16,
	    Registry = 0x18,
	    MessageBox = 0x19,
	    StartAdvEx2 = 0x1A,
	    GameDATAddress = 0x1B,
	    StartAdvEx3 = 0x1C,
	    LogonChallengeEx = 0x1D,
	    ClientID2 = 0x1E,
	    LeaveGame = 0x1F,
	    DisplayAd = 0x21,
	    NotifyJoin = 0x22,
	    Ping = 0x25,
	    ReadUserData = 0x26,
	    WriteUserData = 0x27,
	    LogonChallenge = 0x28,
	    LogonResponse = 0x29,
	    CreateAccount = 0x2A,
	    SystemInfo = 0x2B,
	    GameResult = 0x2C,
	    GetIconData = 0x2D,
	    GetLadderData = 0x2E,
	    FindLadderUser = 0x2F,
	    CDKey = 0x30,
	    ChangePassword = 0x31,
	    CheckDataFile = 0x32,
	    GetFileTime = 0x33,
	    QueryRealms = 0x34,
	    Profile = 0x35,
	    CDKey2= 0x36,
	    LogonResponse2 = 0x3A,
	    CheckDataFile2 = 0x3C,
	    CreateAccount2 = 0x3D,
	    LogonRealmEx = 0x3E,
	    StartVersioning2 = 0x3F,
	    QueryRealms2 = 0x40,
	    QueryAdUrl = 0x41,
	    WarcraftGeneral = 0x44,
	    NetGamePort = 0x45,
	    NewsInfo = 0x46,
	    OptionalWork = 0x4A,
	    ExtraWork = 0x4B,
	    RequiredWork = 0x4C,
	    Tournament = 0x4E,
	    AuthInfo = 0x50,
	    AuthCheck = 0x51,
	    AccountCreate = 0x52,
	    AccountLogon = 0x53,
	    AccountLogonProof = 0x54,
	    AccountChange = 0x55,
	    AccountChangeProof = 0x56,
	    AccountUpgrade = 0x57,
	    AccountUpgradeProof = 0x58,
	    SetEmail = 0x59,
	    ResetPassword = 0x5A,
	    ChangeEmail = 0x5B,
	    SwitchProduct = 0x5C,
	    Warden = 0x5E,
	    GamePlayerSearch = 0x60,
	    FriendsList = 0x65,
	    FriendsUpdate = 0x66,
	    FriendsAdd = 0x67,
	    FriendsRemove = 0x68,
	    FriendsPosition = 0x69,
	    ClanFindCanidates = 0x70,
	    ClanInviteMultiple = 0x71,
	    ClanCreationInvitation= 0x72,
	    ClanDisband = 0x73,
	    ClanMakeChieftain = 0x74,
	    ClanInfo = 0x75,
	    ClanQuitNotify = 0x76,
	    ClanInvitation = 0x77,
	    ClanRemoveMember = 0x78,
	    ClanInvitationResponse = 0x79,
	    ClanRankChange = 0x7A,
	    ClanSetMOTD = 0x7B,
	    ClanMOTD = 0x7C,
	    ClanMemberList = 0x7D,
	    ClanMemberRemoved = 0x7E,
	    ClanMemberStatusChange = 0x7F,
	    ClanMemberRankChange = 0x81,
	    ClanMemberInformation = 0x82
    }

    public partial class Constants
    {
        public const int MAX_PACKET_ID = 0x83;
    }
}
