<?php


/**
 * This class adds structure of 'epgp_items' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 04/03/09 03:21:38
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class EpgpItemsMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.EpgpItemsMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(EpgpItemsPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(EpgpItemsPeer::TABLE_NAME);
		$tMap->setPhpName('EpgpItems');
		$tMap->setClassname('EpgpItems');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addColumn('NAME', 'Name', 'VARCHAR', true, 255);

		$tMap->addForeignKey('AWARDED_TO', 'AwardedTo', 'INTEGER', 'epgp_roster', 'ID', true, null);

		$tMap->addForeignKey('AWARDED_AT', 'AwardedAt', 'INTEGER', 'epgp_raids', 'ID', true, null);

		$tMap->addColumn('ITEMID', 'Itemid', 'INTEGER', true, null);

		$tMap->addColumn('BASEVAL', 'Baseval', 'FLOAT', true, null);

		$tMap->addColumn('INFLATEDVAL', 'Inflatedval', 'FLOAT', true, null);

	} // doBuild()

} // EpgpItemsMapBuilder
